---
title: "Disciplina de Introdução à Programação"
tbl-colwidths: [5,5,5,12,5,5,5]
---

Hub para todos os recursos relevantes referentes à disciplina de **Introdução à Programação**, lecionada para os alunos do curso de **Ciências Econômicas** da [Faculade Belavista](https://faculdadebelavista.edu.br/), no primeiro semestre de 2025.

::: column-screen-inset-right
| Aula |   Data   | Linguagem | Tópico                                        | Slides                                                             |
|:----:|:--------:|:---------:|-----------------------------------------------|--------------------------------------------------------------------|
| 1    | 25/2     | Python    | Introduction to Programming                   | [🖥](/aulas/slides-class-1.html "Class Slides 1")                  |
| 2    | 28/2     | Python    | Functions and Variables                       | [🖥](/aulas/slides-class-2.html "Class Slides 2")                  |
| 3    | 4/3      | Python    | Data Types & Operators                        | [🖥](/aulas/slides-class-3.html "Class Slides 3")                  |
| 4    | 7/3      | Python    | Writing Functions                             | [🖥](/aulas/slides-class-4.html "Class Slides 4")                  |
| 5    | 11/3     | Python    | Conditionals                                  | [🖥](/aulas/slides-class-5.html "Class Slides 5")                  |
| 6    | 14/3     | Python    | Data Structures: Lists                        | [🖥](/aulas/slides-class-6.html "Class Slides 6")                  |
| 7    | 18/3     | Python    | Loops: while                                  | [🖥](/aulas/slides-class-7.html "Class Slides 7")                  |
| 8    | 21/3     | Python    | Loops: for                                    | [🖥](/aulas/slides-class-8.html "Class Slides 8")                  |
| 9    | 25/3     | Python    | Data Structures: Dictionaries                 | [🖥](/aulas/slides-class-9.html "Class Slides 9")                  |
| 10   | 28/3     | Python    | Input / Output Data                           | [🖥](/aulas/slides-class-10.html "Class Slides 10")                |
| 11   | 28/3     | Python    | Storing Data (.xlsx, .csv)                    | [🖥](/aulas/slides-class-11.html "Class Slides 11")                |
| 12   | 1/4      | Python    | List Comprehension                            | [🖥](/aulas/slides-class-12.html "Class Slides 12")                |
| 13   | 4/4      | Python    | Lambda Functions                              | [🖥](/aulas/slides-class-13.html "Class Slides 13")                |
| 14   | 8/4      | Python    | Exception Handling                            | [🖥](/aulas/slides-class-14.html "Class Slides 14")                |
| 15   | 11/4     | Python    | Object-Oriented Programming (OOP) I           | [🖥](/aulas/slides-class-15.html "Class Slides 15")                |
| 16   | 15/4     | Python    | Object-Oriented Programming (OOP) II          | [](){aria-label="Aula 26"}                                         |
| 17   | 22/4     | Python    | Review Geral de Python                        | [](){aria-label="Aula 27"}                                         |
| 18   | 29/4     | R         | Functions and Conditionals                    | [](){aria-label="Aula 26"}                                         |
| 19   | 6/5      | R         | Loops: for &amp; while                          | [](){aria-label="Aula 27"}                                       |
| 20   | 13/5     | R         | Data Structures in R                          | [](){aria-label="Aula 26"}                                         |
| 21   | 20/5     | R         | The apply family I                            | [](){aria-label="Aula 27"}                                         |
| 22   | 27/5     | R         | Introduction to Tidyverse                     | [](){}                                                             |
| 23   | 3/6      | R         | Data Visualization in R I                     | [](){aria-label="Aula 19"}                                         |
| 24   | 10/6     | R         | Data Manipulation in R                        | [](){aria-label="Aula 19"}                                         |
| 25   | 17/6     | R         | Data Visualization in R I                     | [](){aria-label="Aula 19"}                                         |
| 26   | 24/6     | R         | Joining Data in R                             | [](){aria-label="Aula extra"}                                      |
| 27   | 1/7      | R         | Maps in R I - leaflet                         | [](){aria-label="Aula 23"}                                         |
| 28   | 8/7      | R         | Quarto                                        | [](){aria-label="Aula 24"}                                         |
| 29   | 15/7     | Python    | Pandas I                                      | [](){aria-label="Aula 25"}                                         |
| 30   | 18/7     | Python    | Pandas II                                     | []()                                                               |
:::