---
title: "Disciplina de Introdução à Programação"
tbl-colwidths: [5,5,5,15,10,10,10]
---

**Material de Apoio** disponível para a disciplina. Contém os seguintes recursos, distribuiídos para cada parte da segunda etapa da matéria:

- **Material Oficial:** recomendação de leitura do livro da Bibliografia 
- **Material Alternativo:** algum vídeo com explicação detalhada de algum conceito trabalhado em sala
- **Guia de Estudos:** material desenvolvido por prompts ao ChatGPT

::: column-screen-inset-right
| Aula | Linguagem | Tópico                          | Material Oficial                                                                                           | Material Alternativo                                                                  | Guia de Estudos                                                                                             | Resposta Exercícios |
|:----:|-----------|---------------------------------------------------------|------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------|---------------------|
| 1    | Python    | Introduction to Programming     | []()                                                                                                       | []()                                                                                  | []()                                                                                                        | []()                |
| 2    | Python    | Functions and Variables         | [Python 101](https://python.swaroopch.com/first_steps.html)    |   [O que são `variables`?](https://www.youtube.com/watch?v=LKFrQXaoSMQ)    | [Guia #2](https://docs.google.com/document/d/1JJIbkmG1Fhv5JZFbHucs0kdkSZub8pOAg8PQMJRn59Q/edit?usp=sharing)   |[In-class #1](https://docs.google.com/document/d/16fTxAX9tt4ke68_9uSve5NsUp77Y1FVUbEkyVbptc7s/edit?usp=sharing)    |
| 3    | Python    | Data Types & Operators          | [Basic of Everything](https://python.swaroopch.com/basics.html)                                              | [Alguns tipos de dados](https://realpython.com/python-data-types/)                      | [Guia #3](https://docs.google.com/document/d/1PoWW36ApT4njzUD98yAoQWD7mwTOkAGLNKIjqPU6SiE/edit?usp=sharing)   | [In-class #2](https://docs.google.com/document/d/1DUNUsmM2uPWjr6M1PpK8tlEaB2gyDNfPBfPXzU3q6ME/edit?usp=sharing)                |
| 4    | Python    | Writing Functions               | [Defining Functions](https://docs.python.org/3/tutorial/controlflow.html#defining-functions)                   | [Como escrever funções?](https://www.youtube.com/watch?v=mSoEjBpJUJ0)                     | [Guia #4](https://docs.google.com/document/d/1fdEZH6rpQyueTacaQ3jryk-Bd7fgVWq7CyRb25TF-n0/edit?usp=sharing)   | [In-class #3](https://docs.google.com/document/d/19NBRRZ4Js3KX1Il_rqrRmCtuKUJDWRlPllX5NMfDySg/edit?usp=sharing)                |
| 5    | Python    | Conditionals                    | [Intro - Conditionals](https://www.w3schools.com/python/python_conditions.asp)                               | [Intermediate](https://www.youtube.com/watch?v=fxszBuW3V-o)                              | [Guia #5](https://docs.google.com/document/d/1XZXook-l8kWx3gjIKc6_GcJxEQtRSiIBv4HBDi3F4BY/edit?usp=sharing)   | [In-class #4](https://docs.google.com/document/d/113Sjh-1NyHpJ0MJD3k8y5tf49X7NST7-OaicezXdDUw/edit?usp=sharing)                |
| 6    | Python    | Data Structures: Lists          | [Intro to Lists](https://www.w3schools.com/python/python_lists.asp)                                           | [Video](https://www.youtube.com/watch?v=MwyD9PmyW3k)                                    | [Guia #6](https://docs.google.com/document/d/16FKf1QwjeUCScKmqRyUSgp5If_2JZMyiwpypuqEk8ew/edit?usp=sharing)   | []()                |
| 7    | Python    | Loops: while                    | [Intro to While Loops](https://www.w3schools.com/python/python_while_loops.asp)                              | [Video](https://www.youtube.com/watch?v=rRTjPnVooxE&t=4s)                                | [Guia #7](https://docs.google.com/document/d/1QIPP07eRcURHBCCAJgumcoDoDCDG-Cn_aoEfgDQm7EI/edit?usp=sharing)                                                                                                        | []()                |
| 8    | Python    | Loops: for                      | [Intro to For Loops](https://www.w3schools.com/python/python_for_loops.asp)                               | [Vídeo](https://www.youtube.com/watch?v=KWgYha0clzw)                         | [Guia #8](https://docs.google.com/document/d/1RU915YjpdA994HJKx2fkrTYg3IGosQJYcsqVnil-8oI/edit?usp=sharing)                                                                                                        | []()                |
| 9    | Python    | Data Structures: Dictionaries   | [Intro to Dict](https://docs.python.org/3/tutorial/datastructures.html)                                    | [Video](https://www.youtube.com/watch?v=2IsF7DEtVjg)          | [Guia #9](https://docs.google.com/document/d/1bJ5GVNUO1HfM_4sejsZCqfvqF3wD25FXfeedE2FOIfw/edit?usp=sharing)    | []()                |
| 10   | Python    | Input / Output Data             | [File I/O Pyhon](https://muzny.github.io/csci1200-notes/10/1/fileio.html)                         | [Video CS50 (excelente!)](https://www.youtube.com/watch?v=KD-Yoel6EVQ)             | [Guia #10](https://docs.google.com/document/d/1u-vpE96V7zHjB9IxNMUU606i3OueWtbMVgrXnNHMszM/edit?usp=sharing)                                                                                                        | []()                | 
| 12   | Python    | List Comprehension              | [Intro to List Comp.](https://www.w3schools.com/python/python_lists_comprehension.asp) | [Video](https://www.youtube.com/watch?v=AhSvKGTh28Q)| [Guia #11](https://docs.google.com/document/d/1j-Ahu4KxjywQoXqPvLql9UfOpMk40nOpAUKi0WJkwQE/edit?usp=sharing)                                                                                                        | []()                |
| 13   | Python    | Lambda Functions                | [Lambda Functions](https://www.geeksforgeeks.org/python-lambda-anonymous-functions-filter-map-reduce/)  | [Vídeo](https://www.youtube.com/watch?v=hYzwCsKGRrg) | [Guia #12](https://docs.google.com/document/d/10K3cYDqFIG8NYRyybckUH0SVHttUQiSrDDAegfzOb2k/edit?usp=sharing)                                                                                                        | []()                |
| 14  | Python | Exception Handling | [Intro do Exceptions](https://docs.python.org/3/tutorial/errors.html) | [Vídeo](https://www.youtube.com/watch?v=NIWwJbo-9_8) | [Guia #13](https://docs.google.com/document/d/1eLVA_x9IqbYiZYb5KmzAecSHMh0SL0VMd2bYYr4nrSg/edit?usp=sharing)  |
| 15  | Python | OOP I | [Intro OOP](https://www.datacamp.com/tutorial/python-oop-tutorial) | [Vídeo](https://www.youtube.com/watch?v=q2SGW2VgwAM) | [Guia #14](https://docs.google.com/document/d/1t6u3xT6xafo9T0KEjMmcCGp8XFXraY5NygJi01KukyY/edit?usp=sharing)  |
| 16  | Python | OOP II | []() | []() | []()  |
:::